### PR TITLE
add zstd

### PR DESCRIPTION
**Pull request by ksurl**
add support for zstd compression

### CODE REVIEW

**Comment by ksurl** [comment]
~~running tar manually in the container works but it fails when calling it from the docker cli. any ideas?~~

~~manual command:~~

~~`tar -C /volume -I zstd -cf /backup/test.zstd ./`~~

~~via container with local test image:~~
~~`docker run --rm -v test:/volume:ro volume-backup:test backup -c zstd - > /folder/backup.zstd`~~

~~via image would just print the usage text and exit~~

update: ignore the error. I was still using your image in my script, not the test image. it works fine. should be good to merge

**Comment by ksurl** [comment]
oops ignore the error. I was still using your image in my script, not the test image. it works fine. should be good to merge

**Comment by loomchild** [comment]
Thanks a lot for your contribution - I will test it and merge it in a few days (focusing now on FOSDEM / https://fosdem.sojourner.rocks/ 😅)

**Comment by ksurl** [comment]
any update on this?

**Comment by loomchild** [comment]
Not yet.

**Comment by loomchild** [comment]
Hi, it seems to work OK. I will merge it. (and add -zstd to the usage message). Thanks for your help and sorry for delay.

**Pull request merged**
