### PR TITLE
fix zstd restore

### PR DESCRIPTION
**Pull request by ksurl**

### CODE REVIEW

**Comment by loomchild** [comment]
Thanks for submitting the PR. 

However, I am not sure what's the issue that you are fixing. 

The current code seems to be able to restore `zst` archives correctly (tested using the latest version pulled from dockerhub). Also, when I run `ls -al /usr/bin/unzstd` in my container, I get:

    lrwxrwxrwx    1 root     root             4 Mar 20 19:45 /usr/bin/unzstd -> zstd

(meaning `zstd` and `unzstd` are the same binary)

If restore doesn't work for you using the latest version, could you describe steps to reproduce the issue please?

**Comment by ksurl** [comment]
It would print nothing and no files restored. maybe an environment issue on my end. if it works for you then I can close this PR

**Comment by loomchild** [comment]
I want to get to the bottom of this - It would be great if you could share the exact commands you are running to backup and restore. Also make sure to run `docker pull loomchild/volume-backup` to get the latest image.

**Comment by ksurl** [comment]
I was confused by my bindmount volume backup script which I based on this and thought it also happened with the docker image. It was backing up the absolute path and restoring the full path into the relative path so it would look like /folder/volumes/folder/volumes/$volume rather than /folder/volumes/$volume. I'll delete this branch. fixed my script by using -C to use target directory as the root in the tar file instead of the full path.

**Comment by loomchild** [comment]
OK, clear, the script is already using -C. Thanks for info.

**Pull request closed without merging**
